dist: xenial
language: python
python:
    - 3.7

cache:
    directories:
        - $HOME/.blender-cache

matrix:
    include:
        - name: Blender 2.80
          env: BLENDER_VERSION=2.80 MAKE_OPTION=export-blends
        - name: Blender 2.81
          env: BLENDER_VERSION=2.81 MAKE_OPTION=all

before_install:
    - sudo apt-get update
    - pip install --upgrade pip
    - pip install --upgrade setuptools

install:
    - sudo apt-get install --no-install-recommends -y libsdl1.2debian libglu1 python3-pip
    - pip install -r requirements.txt
    - bash tests/install_blender.sh ${BLENDER_VERSION}
    - source .envs

script:
    - make ${MAKE_OPTION} BLENDER=$BLENDER_BIN PYLINT='python3 -m pylint'

after_failure:
    - make update-examples
    - git diff HEAD > tests_scenes_diff.patch
    - cat tests_scenes_diff.patch
    - echo "scene diff path ends"
